### ISSUE TITLE
Incorrect battery.voltage scaling for CyberPower UT850EG-FR

### ISSUE THREAD

**Issue by flis-mateusz** [networkupstools/nut#2983]
Hi, I'm using a CyberPower UT850EG-FR UPS with the usbhid-ups driver on Raspberry Pi OS (also tested on Ubuntu 22.04).

The battery.voltage is shown as 91.3, which seems obviously wrong, especially considering the battery.voltage.nominal is 12.

```
battery.voltage: 91.3
battery.voltage.nominal: 12
```

From debug logs (usbhid-ups -DD), I found:
```
Path: UPS.PowerSummary.Voltage, Type: Input, ReportID: 0x20, Offset: 8, Size: 16, Value: 137
```
which corresponds to about 13.7V (137 × 0.1), the expected battery voltage.

During startup, the driver logs: `cps_adjust_battery_scale: battery readings will be scaled by 2/3` which seems to cause the reported voltage to be incorrectly scaled (multiplied by 1.5), resulting in 91.3 instead of 13.7.

Is there a way to disable or configure this automatic battery voltage scaling in the driver?
Thanks for any help or advice!

**Comment by jimklimov** [comment]
Thanks for pinpointing the message. Logic nearby goes `if( (batt_volt / batt_volt_nom) > battery_voltage_sanity_check )...` where `battery_voltage_sanity_check` = 1.4.

So I guess it takes the raw voltage number (137), finds it is much larger than 12, multiplies by 2/3 and gets 91.3. So the problem is about not dividing 137 by 10.

Can you please check lines near that `Path` report (maybe at higher debug verbosity), if there are entries about units of measurement and/or a factor (e.g. `0.1` or `10^-1` here)?

**Comment by jimklimov** [comment]
Currently there is no setting/override for battery_scale so it is down to guesswork (applied to some productid's).

Which NUT version? There were broken report descriptor fixes for cps-hid that evolved across 2.8.x releases. It would be helpful to check with a custom build of current code, maybe the issie is already solved, maybe not...

**Comment by flis-mateusz** [comment]
I initially tested with `driver.version: 2.7.4`. Afterwards, I installed `driver.version: 2.8.3.464-464+g2dce981ef`. Unfortunately, the issue remains - the reported battery.voltage is still around 86.7.

Below is a snippet from the debug log:
```
 138.286564     Path: UPS.PowerSummary.RunTimeToEmpty, Type: Feature, ReportID: 0x21, Offset: 0, Size: 16, Value: 6570
 138.286630     send_to_all: SETINFO battery.runtime "6570"
 138.286685     Entering libusb_get_report
 138.536594     Report[get]: (3 bytes) => 3f 78 00
 138.536668     PhyMax = 0, PhyMin = 0, LogMax = 65535, LogMin = 0
 138.536722     Unit = 00f0d121, UnitExp = 6
 138.536775     Exponent = -1
 138.536834     Path: UPS.PowerSummary.ConfigVoltage, Type: Feature, ReportID: 0x3f, Offset: 0, Size: 16, Value: 12
 138.536899     Report[buf]: (4 bytes) => 20 64 14 05
 138.536952     PhyMax = 0, PhyMin = 0, LogMax = 65535, LogMin = 0
 138.537006     Unit = 00f0d121, UnitExp = 6
 138.537058     Exponent = -1
 138.537116     Path: UPS.PowerSummary.Voltage, Type: Feature, ReportID: 0x20, Offset: 8, Size: 16, Value: 130
 138.537173     cps_battvolt_fun: battery_scale = 0.667
 138.537235     Entering libusb_get_report
 138.769139     Report[get]: (2 bytes) => 25 03
 138.769251     PhyMax = 0, PhyMin = 0, LogMax = 255, LogMin = 0
 138.769307     Unit = 00000000, UnitExp = 0
 138.769360     Exponent = 0
 138.769420     Path: UPS.Output.PercentLoad, Type: Feature, ReportID: 0x25, Offset: 0, Size: 8, Value: 3
 138.769486     send_to_all: SETINFO ups.load "3"
```
Let me know if you want me to test anything else or provide more logs.

**Comment by jimklimov** [comment]
Thanks! So it seems they tried to make a correct report, but failed to: 

These lines suggest they report a raw value 10x larger than the standard unit (integer amount of tenths of the unit):
```
Exponent = -1
```

As a quick check, `hex(120) = 0x0078` and `hex(1300) = 0x0514` - we see those hexes (in inverse order) in the Report bytes for nominal (12V) and actual voltages (13V is ok for a charged PbAc, up to 13.7V is common, up to 15V is rare - e.g. during pulse charging to clean the chemistry, if supported).

So for `UPS.PowerSummary.Voltage` they claim 1300 tenths of V which is 130V, the exponent here should have been `-2` to get 13.00V from that reading.

If you are into coding (at least, you did manage to build current NUT :) ) - check `drivers/cps-hid.c`: in the end there is a `cps_fix_report_desc()` method.

Try adding logic similar to cases already present, which would sanity-check ReportID 0x20 (32 decimal) that e.g. for values in range 1000..1600 (or 100..160, not sure if that part deals with raw readings and exponents or with calculation results) it would divide by 10.

Or actually it may be more straightforward to update `cps_adjust_battery_scale()` (where it decides about `2.0/3` factor) with such logic, to keep all these eggs in one basket.

**Comment by prabathbr** [comment]
https://github.com/networkupstools/nut/issues/3142

I get the correct voltage with NUT-RELEASE-2.8.4. My UPS is CyberPower UT850EG. I believe `-FR` means just the socket type?

```
battery.voltage: 13.7
battery.voltage.nominal: 12
```
